config/routes.rb
Rails.application.routes.draw do
    root 'pages#homepage'
    devise_for :users
    
    post 'posts/add' => 'posts#create'
end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :user
    validates :user_id, :presence => true
    validates :content, :presence => true, :length => {:maximum => 140}
    
    default_scope { order('created_at DESC') }
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
    belongs_to :follower, :class_name => "User"
    belongs_to :followed, :class_name => "User"
    validates :follower_id, :presence => true
    validates :followed_id, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
      :recoverable, :rememberable, :trackable, :validatable
    
    has_many :relations, :class_name => "Relationship", :foreign_key => "follower_id", :dependent => :destroy
    has_many :passive_relations, :class_name => "Relationship", :foreign_key => "followed_id", :dependent => :destroy
    has_many :following, :through => :relations, :source => :followed
    has_many :followers, :through => :relations, :source => :follower
    has_many :posts
    
    has_attached_file :picture, styles: { medium: "300x300>", thumb: "150x150>" }, default_url: "/images/users/:style/missing.png"
    validates_attachment_content_type :picture, content_type: /\Aimage\/.*\Z/
    
    # Follow a user
    def follow(o_user)
        relations.create(:followed_id => o_user.id)
    end
    # unfollow a user
    def unfollow(o_user)
        relations.find_by(:followed_id => o_user.id).destroy()
    end
    # is following a user 
    def following?(o_user)
        return following.include(o_user)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
    def homepage
        per_page = 50
        if current_user.nil? == false
            @newPost = Post.new()
            user_and_follower_id = [current_user.id] + current_user.following_ids
            @posts = Post.where(:user_id => user_and_follower_id).limit(per_page)
        end
    end
    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :set_post, only: [:edit, :update, :destroy]

    # GET /posts/new
    def new
        @post = Post.new
    end

    # GET /posts/1/edit
    def edit
    end

    # POST /posts
    # POST /posts.json
    def create
        @post = Post.new(post_params)
        @post.user = current_user

        respond_to do |format|
            if @post.save
                format.html { redirect_to root_path, notice: 'Post was successfully created.' }
                format.json { render :show, status: :created, location: @post }
            else
                abort @post.errors.inspect
                format.html { render :new }
                format.json { render json: @post.errors, status: :unprocessable_entity }
            end
        end
    end

    # PATCH/PUT /posts/1
    # PATCH/PUT /posts/1.json
    def update
        respond_to do |format|
            if @post.update(post_params)
                format.html { redirect_to @post, notice: 'Post was successfully updated.' }
                format.json { render :show, status: :ok, location: @post }
            else
                format.html { render :edit }
                format.json { render json: @post.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /posts/1
    # DELETE /posts/1.json
    def destroy
        @post.destroy
        respond_to do |format|
            format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
        @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
        params.require(:post).permit(:content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    # Populate @user
    before_action :set_user, only: [:show, :edit, :update, :destroy]

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
        @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
        params.require(:user).permit(:name, :email, :picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
    
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="favicon.ico">

        <title>Cover Template for Bootstrap</title>

        <!-- Stylesheet -->
        <%= stylesheet_link_tag('application', media: 'all', 'data-turbolinks-track' => true) %>
        <%= csrf_meta_tags %>        
        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        
        <div class="container">
            <%= render('shared/header') %>

            <div class="row">
                <div class="col-md-12">
                    <p class="notice"><%= notice %></p>
                    <p class="alert"><%= alert %></p>
                </div>
            </div>

            <%= yield %>
            <%= render('shared/footer') %>
        </div> 

        <%= javascript_include_tag('application', 'data-turbolinks-track' => true) %>
    </body>
</html>

app/views/pages/_feedpage.html.erb
<section class="page-feed">
    <div class="row">
        <div class="col-md-4">
            <p class="text-center">
                <%= image_tag(current_user.picture) %>
                <%= current_user.email %>
            </p>
        </div>
        <div class="col-md-8">
            <%= bootstrap_form_for(@newPost, url: posts_add_path()) do |f| %>
                <%= f.text_area :content %>
                <%= f.submit %>
            <% end %>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <% if @posts.any? %>
                <ul class="posts-list">
                    <% @posts.each do |post| %>
                        <li class="row">
                            <div class="col-md-4">
                                <p class="text-center">
                                    <%= image_tag(post.user.picture) %><br />
                                    <%= post.user.name %> le <%= post.created_at.strftime("%d-%m-%Y %H:%M") %>
                                </p>                            
                            </div>
                            <div class="col-md-8"><%= post.content %></div>                        
                        </li>
                    <% end %>
                </ul>
            <% end %>
        </div>
    </div>
</section>

app/views/pages/homepage.html.erb
<% if user_signed_in? %>
    <%= render('feedpage') %>
<% else %>
    <div class="inner cover">
        <h1 class="cover-heading">Twitter Tools</h1>
        <p class="lead">Cover is a one-page template for building simple and beautiful home pages. Download, edit the text, and add your own fullscreen background photo to make it your own.</p>
        <p class="lead">
            <a href="#" class="btn btn-lg btn-default">Learn more</a>
        </p>
    </div>
<% end %>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.content %></td>
        <td><%= post.user_id %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user_id %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/shared/_header.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">Zwitter</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="<%= "active" if current_page?('/')  %>" >
                    <%= link_to('Home', root_url()) %>
                </li>
                <li><%= link_to('Sign up', new_user_registration_path()) %></li>
                <li><%= link_to('Sign in', new_user_session_path()) %></li>
            </ul>
        </div>
    </div>
</nav>

app/views/users/_form.html.erb
<%= bootstrap_form_for(@user) do |f| %>
    <%= f.text_field :name %>
    <%= f.text_field :email %>
    <%= f.file_field :picture %>
    <%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Email</th>
            <th colspan="3"></th>
        </tr>
    </thead>

    <tbody>
        <% @users.each do |user| %>
            <tr>
                <td><%= user.name %></td>
                <td><%= user.email %></td>
                <td><%= link_to 'Show', user %></td>
                <td><%= link_to 'Edit', edit_user_path(user) %></td>
                <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
        <% end %>
    </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>